// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Verificar que las variables de entorno estén configuradas
if (!SUPABASE_URL) {
  console.error('❌ VITE_SUPABASE_URL no está configurada');
  console.error('📝 Crea un archivo .env.local en la raíz del proyecto con:');
  console.error('   VITE_SUPABASE_URL=https://tu-proyecto.supabase.co');
  console.error('   VITE_SUPABASE_ANON_KEY=tu-clave-anonima');
  throw new Error('VITE_SUPABASE_URL es requerida. Ver console para instrucciones.');
}

if (!SUPABASE_ANON_KEY) {
  console.error('❌ VITE_SUPABASE_ANON_KEY no está configurada');
  console.error('📝 Crea un archivo .env.local en la raíz del proyecto con:');
  console.error('   VITE_SUPABASE_URL=https://tu-proyecto.supabase.co');
  console.error('   VITE_SUPABASE_ANON_KEY=tu-clave-anonima');
  throw new Error('VITE_SUPABASE_ANON_KEY es requerida. Ver console para instrucciones.');
}

// Log de configuración (solo en desarrollo)
if (import.meta.env.MODE === 'development') {
  console.log('✅ Supabase configurado correctamente');
  console.log(`   URL: ${SUPABASE_URL.substring(0, 30)}...`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Importante para OAuth redirects
  }
});