-- Seed data for job offers and teacher applications
-- This migration creates sample data for testing and development

-- Insert job offers from various institutions
-- Note: These will reference institutions by name, adjust IDs as needed after institutions are created

-- Function to get institution id by name
CREATE OR REPLACE FUNCTION get_institution_id_by_name(institution_name TEXT)
RETURNS UUID AS $$
  SELECT id FROM public.institutions WHERE name = institution_name LIMIT 1;
$$ LANGUAGE SQL;

-- Insert sample job offers
INSERT INTO public.job_offers (
  institution_id, 
  title, 
  description, 
  requirements, 
  responsibilities,
  subject_area, 
  job_type, 
  status,
  salary_min,
  salary_max,
  location,
  benefits,
  vacancies,
  application_deadline,
  start_date,
  published_at
) VALUES
  (
    get_institution_id_by_name('Universidad Central de Venezuela'),
    'Profesor de Matemáticas Avanzadas',
    'Buscamos un profesor altamente calificado para impartir cursos de matemáticas a nivel universitario. El candidato ideal tendrá experiencia en investigación y docencia.',
    ARRAY['Doctorado en Matemáticas o áreas afines', 'Mínimo 3 años de experiencia docente', 'Publicaciones en revistas indexadas', 'Dominio de inglés técnico'],
    ARRAY['Impartir clases de pregrado y postgrado', 'Dirigir tesis de grado', 'Participar en proyectos de investigación', 'Colaborar en actividades de extensión'],
    'Matemáticas',
    'full_time',
    'active',
    2500.00,
    4000.00,
    'Ciudad Universitaria, Caracas',
    ARRAY['Seguro médico', 'Días de formación continua', 'Acceso a biblioteca digital', 'Apoyo para conferencias'],
    2,
    CURRENT_DATE + INTERVAL '30 days',
    CURRENT_DATE + INTERVAL '60 days',
    now()
  ),
  (
    get_institution_id_by_name('Universidad Simón Bolívar'),
    'Profesor de Ingeniería de Software',
    'Se requiere profesor con experiencia en desarrollo de software y metodologías ágiles para programa de Ingeniería en Computación.',
    ARRAY['Maestría en Computación o Ingeniería de Software', 'Experiencia profesional mínima de 5 años', 'Conocimiento en tecnologías web modernas', 'Certificaciones en metodologías ágiles'],
    ARRAY['Dictar cursos de ingeniería de software', 'Supervisar proyectos de desarrollo', 'Actualizar contenido programático', 'Mentoría de estudiantes'],
    'Ingeniería',
    'full_time',
    'active',
    3000.00,
    4500.00,
    'Valle de Sartenejas, Caracas',
    ARRAY['Seguro HCM', 'Capacitación continua', 'Laboratorios equipados', 'Horario flexible'],
    1,
    CURRENT_DATE + INTERVAL '25 days',
    CURRENT_DATE + INTERVAL '45 days',
    now()
  ),
  (
    get_institution_id_by_name('Colegio San Ignacio'),
    'Profesor de Primaria - Español y Matemáticas',
    'Colegio San Ignacio busca profesor de primaria con vocación de servicio y experiencia en educación básica.',
    ARRAY['Licenciatura en Educación', 'Mínimo 2 años de experiencia', 'Conocimiento del modelo educativo jesuita', 'Manejo de herramientas digitales educativas'],
    ARRAY['Planificar y ejecutar clases', 'Evaluar el progreso de los estudiantes', 'Comunicación con padres y representantes', 'Participar en actividades extracurriculares'],
    'Educación Básica',
    'full_time',
    'active',
    1500.00,
    2200.00,
    'Av. Las Palmas, Chacao, Caracas',
    ARRAY['Seguro médico familiar', 'Vacaciones escolares', 'Formación pedagógica', 'Ambiente de trabajo colaborativo'],
    1,
    CURRENT_DATE + INTERVAL '20 days',
    '2025-09-01',
    now()
  ),
  (
    get_institution_id_by_name('Universidad Metropolitana'),
    'Coordinador Académico - Facultad de Economía',
    'Profesional con experiencia en gestión académica y coordinación de programas educativos.',
    ARRAY['Maestría en Economía o Administración', 'Experiencia mínima de 7 años en docencia universitaria', '3 años en cargos de gestión académica', 'Habilidades de liderazgo'],
    ARRAY['Coordinar programas académicos', 'Supervisar cuerpo docente', 'Desarrollar planes de estudio', 'Gestionar evaluación curricular'],
    'Economía',
    'full_time',
    'active',
    3500.00,
    5000.00,
    'Autopista Petare-Guarenas, Caracas',
    ARRAY['Seguro médico privado', 'Bonos por desempeño', 'Apoyo para estudios doctorales', 'Estacionamiento'],
    1,
    CURRENT_DATE + INTERVAL '35 days',
    CURRENT_DATE + INTERVAL '50 days',
    now()
  ),
  (
    get_institution_id_by_name('Colegio Los Arcos'),
    'Profesor de Ciencias Naturales - Secundaria',
    'Buscamos profesor dinámico para enseñar Biología, Química y Física en educación media.',
    ARRAY['Licenciatura en Educación mención Biología o Química', 'Experiencia en laboratorio', 'Habilidades para trabajo con adolescentes', 'Uso de metodologías activas'],
    ARRAY['Impartir clases de ciencias', 'Coordinar prácticas de laboratorio', 'Preparar estudiantes para olimpiadas científicas', 'Innovar en métodos de enseñanza'],
    'Ciencias',
    'full_time',
    'active',
    1800.00,
    2500.00,
    'Los Ruices, Caracas',
    ARRAY['Seguro médico', 'Material didáctico', 'Formación continua', 'Bono de transporte'],
    2,
    CURRENT_DATE + INTERVAL '15 days',
    '2025-09-15',
    now()
  ),
  (
    get_institution_id_by_name('Instituto Universitario de Tecnología Industrial Rodolfo Loero Arismendi'),
    'Instructor de Programación y Bases de Datos',
    'Se requiere instructor técnico para programas de TSU en Informática.',
    ARRAY['TSU o Ingeniería en Informática', 'Experiencia en desarrollo de software', 'Conocimiento de SQL y bases de datos', 'Manejo de lenguajes de programación modernos'],
    ARRAY['Dictar clases prácticas', 'Evaluar proyectos estudiantiles', 'Actualizar laboratorios', 'Asesorar pasantías'],
    'Tecnología',
    'part_time',
    'active',
    1200.00,
    1800.00,
    'Av. Principal de Los Ruices, Caracas',
    ARRAY['Horario vespertino', 'Posibilidad de tiempo completo', 'Acceso a equipos'],
    2,
    CURRENT_DATE + INTERVAL '40 days',
    CURRENT_DATE + INTERVAL '55 days',
    now()
  ),
  (
    get_institution_id_by_name('Universidad Católica Andrés Bello'),
    'Profesor de Derecho Constitucional',
    'La Facultad de Derecho busca profesor especializado en Derecho Constitucional y Derechos Humanos.',
    ARRAY['Abogado con especialización o maestría', 'Mínimo 5 años de ejercicio profesional', 'Experiencia en litigio constitucional', 'Publicaciones académicas'],
    ARRAY['Impartir cátedras de derecho constitucional', 'Dirigir trabajos de investigación', 'Participar en clínicas jurídicas', 'Extensión universitaria'],
    'Derecho',
    'part_time',
    'active',
    2000.00,
    3000.00,
    'Urb. Montalbán, La Vega, Caracas',
    ARRAY['Reconocimiento académico', 'Networking profesional', 'Acceso a biblioteca jurídica', 'Flexibilidad horaria'],
    1,
    CURRENT_DATE + INTERVAL '30 days',
    CURRENT_DATE + INTERVAL '60 days',
    now()
  ),
  (
    get_institution_id_by_name('Instituto de Diseño de Caracas'),
    'Profesor de Diseño Gráfico Digital',
    'Diseñador profesional con experiencia en software de diseño y metodologías creativas.',
    ARRAY['Diseñador gráfico titulado', 'Portfolio profesional comprobable', 'Dominio de Adobe Creative Suite', 'Experiencia en diseño UX/UI'],
    ARRAY['Impartir talleres de diseño', 'Evaluar proyectos creativos', 'Coordinar exposiciones', 'Mentoría de portafolios'],
    'Diseño',
    'part_time',
    'active',
    1500.00,
    2200.00,
    'Av. Libertador, Caracas',
    ARRAY['Acceso a software profesional', 'Espacio de taller creativo', 'Red de contactos', 'Horario flexible'],
    1,
    CURRENT_DATE + INTERVAL '20 days',
    CURRENT_DATE + INTERVAL '40 days',
    now()
  ),
  (
    get_institution_id_by_name('Colegio Don Bosco'),
    'Orientador Vocacional',
    'Psicólogo especializado en orientación educativa y vocacional para adolescentes.',
    ARRAY['Psicólogo titulado', 'Especialización en psicología educativa', 'Experiencia con adolescentes', 'Conocimiento de pruebas vocacionales'],
    ARRAY['Orientación individual y grupal', 'Aplicación de pruebas vocacionales', 'Talleres para padres', 'Acompañamiento en elección de carrera'],
    'Orientación',
    'full_time',
    'active',
    1800.00,
    2600.00,
    'Av. Principal de Altamira, Caracas',
    ARRAY['Seguro médico', 'Formación continua', 'Supervisión profesional', 'Vacaciones escolares'],
    1,
    CURRENT_DATE + INTERVAL '25 days',
    '2025-09-01',
    now()
  ),
  (
    get_institution_id_by_name('Instituto Universitario de Tecnología de Administración Industrial'),
    'Profesor de Administración y Contabilidad',
    'Contador público o administrador con experiencia en docencia de materias contables y administrativas.',
    ARRAY['Contador Público o Licenciado en Administración', 'Experiencia profesional mínima 5 años', 'Conocimiento de normativas contables', 'Experiencia docente deseable'],
    ARRAY['Dictar materias del área contable', 'Supervisar prácticas profesionales', 'Actualizar contenidos programáticos', 'Asesoría académica'],
    'Administración',
    'full_time',
    'active',
    2000.00,
    3000.00,
    'Av. Francisco de Miranda, Caracas',
    ARRAY['Seguro HCM', 'Estabilidad laboral', 'Formación pedagógica', 'Bono de fin de año'],
    2,
    CURRENT_DATE + INTERVAL '30 days',
    CURRENT_DATE + INTERVAL '50 days',
    now()
  );

-- Clean up helper function
DROP FUNCTION get_institution_id_by_name(TEXT);
